name: Python云端测试

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: 获取仓库代码

        uses: actions/checkout@v4

      - name: 运行Python测试

        run: python test.py
